// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// allpaths
NumericMatrix allpaths(NumericMatrix adjMatrix, int startNode, int endNode, int maxDepth, int nPilot, int nEstimation);
RcppExport SEXP _social_allpaths(SEXP adjMatrixSEXP, SEXP startNodeSEXP, SEXP endNodeSEXP, SEXP maxDepthSEXP, SEXP nPilotSEXP, SEXP nEstimationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type adjMatrix(adjMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type startNode(startNodeSEXP);
    Rcpp::traits::input_parameter< int >::type endNode(endNodeSEXP);
    Rcpp::traits::input_parameter< int >::type maxDepth(maxDepthSEXP);
    Rcpp::traits::input_parameter< int >::type nPilot(nPilotSEXP);
    Rcpp::traits::input_parameter< int >::type nEstimation(nEstimationSEXP);
    rcpp_result_gen = Rcpp::wrap(allpaths(adjMatrix, startNode, endNode, maxDepth, nPilot, nEstimation));
    return rcpp_result_gen;
END_RCPP
}
